package:
  name: string-art
  version: 1.0

source:
  path: ../

build:
  script: $PYTHON -m pip install --no-deps .

requirements:
  host:
    - python >=3.7

  run:
    - conda
    - python >=3.7
    - art

about:
  home: https://github.com/conda/conda-plugin-template
  license: BSD-3-Clause
  license_file: LICENSE
  summary: My string art subcommand plugin
