package:
  name: {{ cookiecutter.project_slug }}
  {{ '{% if GIT_DESCRIBE_TAG is defined and GIT_BUILD_STR is defined %}' }}
  version: {{ '{{ GIT_DESCRIBE_TAG }}+{{ GIT_BUILD_STR }}' }}
  {{ '{% else %}' }}
  version: 0.0.0dev0
  {{ '{% endif %}' }}

source:
  # git_url only captures committed code
  git_url: ../

build:
  number: 0
  noarch: python
  script:
    - python -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python 3.9
    - pip
    - hatchling >=1.12.2
    {% if cookiecutter.use_vcs_version %}- hatch-vcs >=0.2.0{% endif %}
  run:
    - python >=3.9
    - conda >=23.9.0

test:
  requires:
    - python 3.9
  imports:
    - {{ cookiecutter.package_name }}
  # commands:
  #  - conda SUBCOMMAND_HERE --help

about:
  home: https://github.com/{{ cookiecutter.github_user_or_org }}/{{ cookiecutter.github_repo }}
  license: REPLACE-ME  # e.g. MIT, BSD-3-Clause
  license_file: LICENSE
  summary: {{ cookiecutter.project_description }}
  dev_url: https://github.com/{{ cookiecutter.github_user_or_org }}/{{ cookiecutter.github_repo }}
