package:
  name: temp-converter
  version: 1.0

source:
  path: ../

build:
  script: $PYTHON -m pip install --no-deps .

requirements:
  host:
    - python >=3.7
    - cffi>=1.0.0

  run:
    - conda
    - python >=3.7
    - cffi>=1.0.0

about:
  home: https://github.com/conda/conda-plugin-template
  license: BSD-3-Clause
  summary: A custom subcommand written in C that converts Celsius to Fahrenheit
