package:
  name: package-counter
  version: 1.0

source:
  path: ../

build:
  script: $PYTHON -m pip install --no-deps .

requirements:
  host:
    - python >=3.7

  run:
    - conda
    - python >=3.7
    - sympy

about:
  home: https://github.com/conda/conda-plugin-template
  license: BSD-3-Clause
  summary: Displays the number of packages in the environment