package:
  name: multiply
  version: 1.0

source:
  path: ../

build:
  script: $PYTHON -m pip install --no-deps .

requirements:
  host:
    - python >=3.7

  run:
    - conda
    - python >=3.7
    - maturin

about:
  home: https://github.com/conda/conda-plugin-template/subcommand_plugin_examples/rust_subcommand_plugin_tutorial/multiply
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A subcommand written in Rust that multiplies two integers
